# Generated by Django 6.0.4 on 2026-04-25 16:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Events Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_type', models.CharField(blank=True, choices=[('workshop', 'Workshop'), ('meeting', 'Meeting'), ('review', 'Review'), ('training', 'Training'), ('other', 'Other')], default='other', max_length=50)),
                ('intro', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_duration', models.CharField(blank=True, max_length=255)),
                ('event_location', models.CharField(blank=True, max_length=255)),
                ('participants', models.TextField(blank=True)),
                ('overview', wagtail.fields.RichTextField(blank=True)),
                ('objectives', wagtail.fields.RichTextField(blank=True)),
                ('highlights', wagtail.fields.RichTextField(blank=True)),
                ('outcomes', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Event Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
