# Generated by Django 6.0.4 on 2026-04-26 02:20

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='event_type',
            field=models.CharField(blank=True, choices=[('workshop', 'Workshop'), ('meeting', 'Meeting'), ('review', 'Review'), ('training', 'Training'), ('promotional', 'Promotional'), ('pitching', 'Pitching'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='EventPagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.eventpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
