# Generated by Django 6.0.4 on 2026-04-26 07:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Commodity Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CommodityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(blank=True, default='Aquaculture', max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('overview', wagtail.fields.RichTextField(blank=True)),
                ('benefits', wagtail.fields.RichTextField(blank=True)),
                ('cultivation', wagtail.fields.RichTextField(blank=True)),
                ('market_info', wagtail.fields.RichTextField(blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Commodity Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
