# Generated by Django 6.0.4 on 2026-04-25 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_banner_subtitle_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True, default="A multi-institutional program advancing technology transfer, business incubation, and knowledge sharing across Western Mindanao's AANR sector."),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Empowering agricultural communities through innovation, sustainability, and knowledge sharing.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, default='Raise Western Mindanao', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat1_description',
            field=models.CharField(default='Research papers and technical docs', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat1_label',
            field=models.CharField(default='Knowledge Resources', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat1_number',
            field=models.CharField(default='1000', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat2_description',
            field=models.CharField(default='Active researchers and innovators', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat2_label',
            field=models.CharField(default='Community Members', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat2_number',
            field=models.CharField(default='500', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat3_description',
            field=models.CharField(default='Innovation and training initiatives', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat3_label',
            field=models.CharField(default='Active Programs', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat3_number',
            field=models.CharField(default='50', max_length=10),
        ),
    ]
