# Generated by Django 6.0.4 on 2026-06-18 15:18

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='e.g., WMSU (Main Hub)', max_length=255)),
                ('latitude', models.FloatField(help_text='e.g., 6.9186')),
                ('longitude', models.FloatField(help_text='e.g., 122.0620')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('google_maps_url', models.URLField(blank=True, verbose_name='Google Maps Link')),
                ('pop_offset_x', models.IntegerField(default=0, help_text='Use -30 or 30 to shift popup if pins overlap close together.')),
                ('pop_offset_y', models.IntegerField(default=-24, help_text='Default is -24 (places popup right over pin tip).')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_locations', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
