# Generated by Django 6.0.4 on 2026-04-25 02:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_subtitle', models.TextField(blank=True)),
                ('program_rationale', wagtail.fields.RichTextField(blank=True)),
                ('program_objectives_general', wagtail.fields.RichTextField(blank=True)),
                ('program_objectives_specific', wagtail.fields.RichTextField(blank=True)),
                ('org_structure_title', models.CharField(blank=True, default='Our Organizational Structure', max_length=255)),
                ('org_structure_description', models.TextField(blank=True)),
                ('mission', wagtail.fields.RichTextField(blank=True)),
                ('vision', wagtail.fields.RichTextField(blank=True)),
                ('objectives', wagtail.fields.RichTextField(blank=True)),
                ('org_structure_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
