# Generated by Django 6.0.4 on 2026-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcespage',
            name='page_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
