# Generated by Django 6.0.4 on 2026-04-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_commodityitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityitem',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='commodityitem',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
