# Generated by Django 6.0.4 on 2026-04-26 12:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_commodityitem_category_commodityitem_scientific_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodityitem',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='commodityitem',
            name='url',
        ),
        migrations.AddField(
            model_name='commodityitem',
            name='benefits',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='commodityitem',
            name='cultivation',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='commodityitem',
            name='market_info',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='commodityitem',
            name='overview',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
