# Generated by Django 6.0.4 on 2026-04-29 11:17

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_rename_description_commodityitem_short_description_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category_icon', models.CharField(blank=True, default='📁', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, default='from-primary to-accent', help_text='Tailwind gradient e.g. from-primary to-accent', max_length=50)),
            ],
            options={
                'verbose_name': 'Resource Category Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResourceCategoryEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('file_type', models.CharField(blank=True, help_text='e.g. PDF, Video, Link', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='resources.resourcecategorypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
