# Generated by Django 6.0.4 on 2026-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resourcecategorypage_resourcecategoryentryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecategoryentryitem',
            name='date',
            field=models.DateField(blank=True, help_text='Optional date for events or news', null=True),
        ),
        migrations.AlterField(
            model_name='resourcecategoryentryitem',
            name='url',
            field=models.URLField(blank=True, help_text='Link for the event or resource'),
        ),
    ]
